# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 564)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("master.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"    background-color:rgb(54,54,54);\n"
"}\n"
" \n"
"QLabel,QGroupBox\n"
"{\n"
"    color:white;\n"
"    font:12px;\n"
"}\n"
" \n"
"QLineEdit,QPlainTextEdit\n"
"{\n"
"    color:white;\n"
"    font:13px;\n"
" \n"
"    /*边界线 border:none 没有边界*/\n"
"    border:1px solid rgb(128, 138, 135);\n"
" \n"
"    /*背景的颜色*/\n"
"    background: rgb(54, 54, 54);\n"
" \n"
"    /*边角4像素圆滑*/\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"/*鼠标滑动到LineEditor时*/\n"
"QLineEdit::hover\n"
"{\n"
"      color:rgb(250,250,250);  /*字体的颜色*/\n"
"      border-color:rgb(50,480,40);\n"
"      background-color:rgb(47,79,79);\n"
"}\n"
" \n"
"QPushButton\n"
"{\n"
"    background-color:rgb(128, 138, 135);\n"
"    color:white;\n"
"    font:16px;\n"
"    border-radius:6px; \n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#0000ff;\n"
"    background-color:rgb(210, 205, 205); /*改变背景色*/\n"
"    border-style:inset;/*改变边框风格*/\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 80, 261, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.le1.setMinimumSize(QtCore.QSize(0, 40))
        self.le1.setObjectName("le1")
        self.horizontalLayout.addWidget(self.le1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(190, 310, 111, 41))
        self.btn1.setObjectName("btn1")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 150, 261, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.le2.setMinimumSize(QtCore.QSize(0, 40))
        self.le2.setObjectName("le2")
        self.horizontalLayout_2.addWidget(self.le2)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(360, 390, 91, 41))
        self.btn2.setObjectName("btn2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(190, 220, 261, 61))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.le3 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.le3.setMinimumSize(QtCore.QSize(0, 40))
        self.le3.setObjectName("le3")
        self.horizontalLayout_3.addWidget(self.le3)
        self.le4 = QtWidgets.QLineEdit(self.centralwidget)
        self.le4.setGeometry(QtCore.QRect(310, 310, 141, 41))
        self.le4.setObjectName("le4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 30, 71, 31))
        self.label_4.setObjectName("label_4")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(270, 30, 121, 31))
        self.l5.setObjectName("l5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn1.clicked.connect(MainWindow.slot1)
        self.btn2.clicked.connect(MainWindow.slot2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "注册界面"))
        self.label.setText(_translate("MainWindow", "姓名："))
        self.btn1.setText(_translate("MainWindow", "请选择图片"))
        self.label_2.setText(_translate("MainWindow", "年龄："))
        self.btn2.setText(_translate("MainWindow", "确定"))
        self.label_3.setText(_translate("MainWindow", "性别："))
        self.label_4.setText(_translate("MainWindow", "ID："))
        self.l5.setText(_translate("MainWindow", "1"))
